version: "3.8"
services:     
    redis:
      image: redis:6.2-alpine
      restart: always   
      ports:
        - '6379:6379' 
      
    nginx:    
      image: nginx:1.21-alpine
      restart: always           
      ports:
        - "80:80"
        - "443:443"
      container_name: nginx       
      volumes:  
        - ./bin/nginx.conf:/etc/nginx/nginx.conf            
        - ./ssl:/app/ssl
        - ./logs:/app/logs
        - ./db_backups:/app/db_backups  
        - ./client:/app/client                      
      depends_on:
        - web       
    pgdb:
      image: postgres:14-alpine     
      container_name: postgres_db         
      restart : always       
                                          
      environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
          - POSTGRES_HOST=pgdb
          - POSTGRES_PORT=5432
         
                         
      volumes:
          - postgres-data:/var/lib/postgresql/data                 
          - ./logs:/app/logs  
          
      ports:
          - 5432   
    
    web:
      build: 
        context: .                    
      container_name: web      
      restart: always      
      command: bash -c "sh /app/bin/docker_start.sh"      
      ports:
        - "8000:8000"       
      volumes:       
        - static-data:/app/staticfiles
        - media-data:/app/media
        - ./logs:/app/logs         
        - ./db_backups:/app/db_backups
        - ./bin:/app/bin
        - ./commands:/app/commands      
      environment: 
        - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
        - SECRET_KEY=${SECRET_KEY}           
        - DATABASE_NAME=${POSTGRES_DB}
        - DATABASE_USER=${POSTGRES_USER}
        - DATABASE_PASSWORD=${POSTGRES_PASSWORD}     
        - DATABASE_HOST=pgdb                            
        - EMAIL_HOST=${EMAIL_HOST}
        - EMAIL_PORT=${EMAIL_PORT}
        - EMAIL_HOST_USER=${EMAIL_HOST_USER}
        - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}   
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
       
    
      depends_on:
        - pgdb
        - redis 
    
           
         
volumes:
  postgres-data:
  
 

    
     




