# Generated by Django 3.2.8 on 2021-12-02 21:25

import Profil.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Participes', '0001_initial'),
        ('Topic', '0001_initial'),
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Profil.models.user_directory_path, verbose_name='Picture')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='linkedin')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('brandfollow', models.ManyToManyField(to='Brand.BrandModel')),
                ('favorites', models.ManyToManyField(to='Participes.Article')),
                ('interest', models.ManyToManyField(to='Topic.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
